#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.TrackMe.Resource", IsApplication=true)]

namespace Xamarin.TrackMe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int expiration_time_array = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int header = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int user = 2130837506;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int boxProgress = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int boxShare = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int boxUser = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int buttonCancel = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int buttonOk = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int buttonShare = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int checkMeet = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int imageUserIcon = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int imageViewList = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int imageViewShare = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout2 = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070017
			public const int listView = 2131165207;
			
			// aapt resource value: 0x7f070007
			public const int map = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int progressBar1 = 2131165199;
			
			// aapt resource value: 0x7f07000a
			public const int spinnerTime = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int tabHost = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int textDate = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int textMessage = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int textUserName = 2131165204;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Map = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ShareLocation = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SharesList = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StartTracking = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TrackedShareRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TrackList = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int appTitle = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int cancel = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int doYouWantToTrackThePositionOfTheFollowingUser = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int expirationDateError = 2130968593;
			
			// aapt resource value: 0x7f04000e
			public const int expirationTime = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int expireOnArrival = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int gettingTrackInformation = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int invalidReference = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int selectDate = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int shareFailed = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int shareLocation = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int shareMessage = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int shareSubject = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int shareVia = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int shareYourLocation = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int sharingLocation = 2130968594;
			
			// aapt resource value: 0x7f040006
			public const int startTracking = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int startedTracking = 2130968586;
			
			// aapt resource value: 0x7f040015
			public const int touchToOpen = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int trackerNotification = 2130968596;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int header_text = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
